from PyQt5 import QtCore, QtGui, QtWidgets

from Start.DB_Configuration import exe_query


class Ui_customer_booking_window(object):

    def __init__(self):
        self.res = []

    def setupUi(self, customer_booking_window):
        customer_booking_window.setObjectName("customer_booking_window")
        customer_booking_window.resize(1094, 846)
        customer_booking_window.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        customer_booking_window.setStyleSheet("background-color: rgb(197, 223, 255);")
        self.customer_booking_Header_L = QtWidgets.QLabel(customer_booking_window)
        self.customer_booking_Header_L.setGeometry(QtCore.QRect(370, 30, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.customer_booking_Header_L.setFont(font)
        self.customer_booking_Header_L.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customer_booking_Header_L.setStyleSheet("background-color: rgb(255, 97, 100);")
        self.customer_booking_Header_L.setAlignment(QtCore.Qt.AlignCenter)
        self.customer_booking_Header_L.setObjectName("customer_booking_Header_L")
        self.customer_booking_show_room_PB = QtWidgets.QPushButton(customer_booking_window)
        self.customer_booking_show_room_PB.setGeometry(QtCore.QRect(710, 170, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.customer_booking_show_room_PB.setFont(font)
        self.customer_booking_show_room_PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customer_booking_show_room_PB.setStyleSheet("background-color: rgb(37, 255, 201);")
        self.customer_booking_show_room_PB.setObjectName("customer_booking_show_room_PB")
        self.customer_booking_TableWidget = QtWidgets.QTableWidget(customer_booking_window)
        self.customer_booking_TableWidget.setGeometry(QtCore.QRect(40, 280, 1031, 451))
        self.customer_booking_TableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.customer_booking_TableWidget.setObjectName("customer_booking_TableWidget")
        self.customer_booking_TableWidget.setColumnCount(7)
        self.customer_booking_TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(120, 105, 110))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_booking_TableWidget.setHorizontalHeaderItem(6, item)
        self.customer_booking_TableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.customer_booking_Customer_id_LE = QtWidgets.QLineEdit(customer_booking_window)
        self.customer_booking_Customer_id_LE.setGeometry(QtCore.QRect(320, 180, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.customer_booking_Customer_id_LE.setFont(font)
        self.customer_booking_Customer_id_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customer_booking_Customer_id_LE.setObjectName("customer_booking_Customer_id_LE")
        self.customer_booking_Customer_id_L = QtWidgets.QLabel(customer_booking_window)
        self.customer_booking_Customer_id_L.setGeometry(QtCore.QRect(60, 180, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.customer_booking_Customer_id_L.setFont(font)
        self.customer_booking_Customer_id_L.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.customer_booking_Customer_id_L.setStyleSheet("background-color: rgb(219, 255, 58);")
        self.customer_booking_Customer_id_L.setAlignment(QtCore.Qt.AlignCenter)
        self.customer_booking_Customer_id_L.setObjectName("customer_booking_Customer_id_L")

        self.retranslateUi(customer_booking_window)
        QtCore.QMetaObject.connectSlotsByName(customer_booking_window)

        # TODO: SHOW_CUSTOMER_BOOKING_DETAILS_ROOMS
        self.customer_booking_show_room_PB.clicked.connect(self.show_customer_booking_details_rooms)

    def retranslateUi(self, customer_booking_window):
        _translate = QtCore.QCoreApplication.translate
        customer_booking_window.setWindowTitle(_translate("customer_booking_window", "Customer Booking"))
        self.customer_booking_Header_L.setText(_translate("customer_booking_window", "Customer\'s Booking"))
        self.customer_booking_show_room_PB.setText(_translate("customer_booking_window", "Show Rooms"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("customer_booking_window", "Reserv. No. #"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("customer_booking_window", "Room No. #"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("customer_booking_window", "Floor"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("customer_booking_window", "Price Per Night"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("customer_booking_window", "Beds Number"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("customer_booking_window", "Description"))
        item = self.customer_booking_TableWidget.horizontalHeaderItem(6)
        item.setText(_translate("customer_booking_window", "Max Capacity"))
        self.customer_booking_Customer_id_L.setText(_translate("customer_booking_window", "Enter Customer No.#"))

    def show_customer_booking_details_rooms(self):
        self.res = exe_query(f""" 
                                SELECT reservation.Reservation_ID,room.Room_ID,Floor,room.Price_Per_Night,
                                 rt.no_beds,rt.description,room.Maximum_Capacity FROM 
                                reservation JOIN reservation_details ON
                                reservation.Reservation_ID = reservation_details.Reservation_ID
                                JOIN room  on room.Room_ID = reservation_details.Room_ID
                                JOIN room_type rt on room.room_type_id = rt.room_type_id
                                WHERE  reservation.Guest_ID = '{int(self.customer_booking_Customer_id_LE.text())}'
                                ORDER BY Reservation_ID;
                        """)

        row = 0
        self.customer_booking_TableWidget.setRowCount(len(self.res))
        for data in self.res:
            self.customer_booking_TableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(data[0])))
            self.customer_booking_TableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data[1])))
            self.customer_booking_TableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(data[2])))
            self.customer_booking_TableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(data[3])))
            self.customer_booking_TableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(data[4])))
            self.customer_booking_TableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(str(data[5])))
            self.customer_booking_TableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(str(data[6])))

            row += 1
