from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
from Start.DB_Configuration import exe_query
from User.Script.Guest_LoginPage import Ui_loginPage


class Ui_Guest_signup_page(object):

    def setupUi(self, Guest_signup_page):
        Guest_signup_page.setObjectName("Guest_signup_page")
        Guest_signup_page.resize(1107, 846)
        Guest_signup_page.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        icon = QtGui.QIcon.fromTheme("Icon")
        Guest_signup_page.setWindowIcon(icon)
        Guest_signup_page.setStyleSheet("background-color: rgb(199, 233, 255);")
        # Guest_signup_page.setModal(False)
        self.Guest_signup_page_header_L = QtWidgets.QLabel(Guest_signup_page)
        self.Guest_signup_page_header_L.setGeometry(QtCore.QRect(320, 30, 471, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Guest_signup_page_header_L.setFont(font)
        self.Guest_signup_page_header_L.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Guest_signup_page_header_L.setStyleSheet("background-color: rgb(255, 102, 104);")
        self.Guest_signup_page_header_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Guest_signup_page_header_L.setObjectName("Guest_signup_page_header_L")
        self.Firstname_L = QtWidgets.QLabel(Guest_signup_page)
        self.Firstname_L.setGeometry(QtCore.QRect(100, 200, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Firstname_L.setFont(font)
        self.Firstname_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                       "color: rgb(245, 243, 255);")
        self.Firstname_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Firstname_L.setObjectName("Firstname_L")
        self.Family_L = QtWidgets.QLabel(Guest_signup_page)
        self.Family_L.setGeometry(QtCore.QRect(580, 200, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Family_L.setFont(font)
        self.Family_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                    "color: rgb(245, 243, 255);")
        self.Family_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Family_L.setObjectName("Family_L")
        self.Firstname_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.Firstname_LE.setGeometry(QtCore.QRect(340, 200, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Firstname_LE.setFont(font)
        self.Firstname_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Firstname_LE.setObjectName("Firstname_LE")
        self.Signup_Button = QtWidgets.QPushButton(Guest_signup_page)
        self.Signup_Button.setGeometry(QtCore.QRect(300, 720, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Signup_Button.setFont(font)
        self.Signup_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Signup_Button.setAcceptDrops(False)
        self.Signup_Button.setAutoFillBackground(False)
        self.Signup_Button.setStyleSheet("background-color: rgb(208, 209, 255);\n"
                                         "color: rgb(102, 64, 255);")
        self.Signup_Button.setObjectName("Signup_Button")
        self.Family_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.Family_LE.setGeometry(QtCore.QRect(800, 200, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Family_LE.setFont(font)
        self.Family_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Family_LE.setObjectName("Family_LE")
        self.Gender_L = QtWidgets.QLabel(Guest_signup_page)
        self.Gender_L.setGeometry(QtCore.QRect(580, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Gender_L.setFont(font)
        self.Gender_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                    "color: rgb(245, 243, 255);")
        self.Gender_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Gender_L.setObjectName("Gender_L")
        self.BirthDate_L = QtWidgets.QLabel(Guest_signup_page)
        self.BirthDate_L.setGeometry(QtCore.QRect(90, 450, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BirthDate_L.setFont(font)
        self.BirthDate_L.setStyleSheet("background-color: rgb(7, 85, 127);\n"
                                       "color: rgb(255, 249, 249);")
        self.BirthDate_L.setAlignment(QtCore.Qt.AlignCenter)
        self.BirthDate_L.setObjectName("BirthDate_L")
        self.male_RD = QtWidgets.QRadioButton(Guest_signup_page)
        self.male_RD.setGeometry(QtCore.QRect(800, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.male_RD.setFont(font)
        self.male_RD.setStyleSheet("background-color: rgb(255, 111, 111);")
        self.male_RD.setCheckable(True)
        self.male_RD.setObjectName("male_RD")
        self.female_RD = QtWidgets.QRadioButton(Guest_signup_page)
        self.female_RD.setGeometry(QtCore.QRect(950, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.female_RD.setFont(font)
        self.female_RD.setStyleSheet("background-color: rgb(255, 111, 111);")
        self.female_RD.setIconSize(QtCore.QSize(20, 20))
        self.female_RD.setObjectName("female_RD")
        self.Phone_L = QtWidgets.QLabel(Guest_signup_page)
        self.Phone_L.setGeometry(QtCore.QRect(100, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Phone_L.setFont(font)
        self.Phone_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                   "color: rgb(245, 243, 255);")
        self.Phone_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Phone_L.setObjectName("Phone_L")
        self.Address_L = QtWidgets.QLabel(Guest_signup_page)
        self.Address_L.setGeometry(QtCore.QRect(90, 570, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Address_L.setFont(font)
        self.Address_L.setStyleSheet("background-color: rgb(7, 85, 127);\n"
                                     "color: rgb(255, 249, 249);")
        self.Address_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Address_L.setObjectName("Address_L")
        self.Phone_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.Phone_LE.setGeometry(QtCore.QRect(340, 290, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Phone_LE.setFont(font)
        self.Phone_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Phone_LE.setObjectName("Phone_LE")
        self.Address_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.Address_LE.setGeometry(QtCore.QRect(330, 570, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Address_LE.setFont(font)
        self.Address_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Address_LE.setObjectName("Address_LE")
        self.BirthDate_DE = QtWidgets.QDateEdit(Guest_signup_page)
        self.BirthDate_DE.setGeometry(QtCore.QRect(340, 460, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BirthDate_DE.setFont(font)
        self.BirthDate_DE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BirthDate_DE.setStyleSheet("background-color: rgb(231, 255, 248);")
        self.BirthDate_DE.setObjectName("BirthDate_DE")
        self.National_L = QtWidgets.QLabel(Guest_signup_page)
        self.National_L.setGeometry(QtCore.QRect(100, 370, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.National_L.setFont(font)
        self.National_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                      "color: rgb(245, 243, 255);")
        self.National_L.setAlignment(QtCore.Qt.AlignCenter)
        self.National_L.setObjectName("National_L")
        self.National_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.National_LE.setGeometry(QtCore.QRect(340, 370, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.National_LE.setFont(font)
        self.National_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.National_LE.setObjectName("National_LE")
        self.Password_L = QtWidgets.QLabel(Guest_signup_page)
        self.Password_L.setGeometry(QtCore.QRect(580, 370, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Password_L.setFont(font)
        self.Password_L.setStyleSheet("background-color: rgb(85, 85, 127);\n"
                                      "color: rgb(245, 243, 255);")
        self.Password_L.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_L.setObjectName("Password_L")
        self.Password_LE = QtWidgets.QLineEdit(Guest_signup_page)
        self.Password_LE.setGeometry(QtCore.QRect(800, 360, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Password_LE.setFont(font)
        self.Password_LE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Password_LE.setObjectName("Password_LE")
        self.Login_Button = QtWidgets.QPushButton(Guest_signup_page)
        self.Login_Button.setGeometry(QtCore.QRect(620, 720, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Button.setFont(font)
        self.Login_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_Button.setAcceptDrops(False)
        self.Login_Button.setAutoFillBackground(False)
        self.Login_Button.setStyleSheet("background-color: rgb(208, 209, 255);\n"
                                        "color: rgb(102, 64, 255);")
        self.Login_Button.setObjectName("Login_Button")

        self.retranslateUi(Guest_signup_page)
        QtCore.QMetaObject.connectSlotsByName(Guest_signup_page)

        # TODO:SIGNUP_Clicked
        self.Signup_Button.clicked.connect(self.Fill_Guest_Information)

        # TODO:LOGIN_Clicked
        self.Login_Button.clicked.connect(self.Guest_Login_Window)

    def retranslateUi(self, Guest_signup_page):
        _translate = QtCore.QCoreApplication.translate
        Guest_signup_page.setWindowTitle(_translate("Guest_signup_page", "SignUp Page"))
        self.Guest_signup_page_header_L.setText(_translate("Guest_signup_page", "Welcome To Guest Registeration Page"))
        self.Firstname_L.setText(_translate("Guest_signup_page", "First name"))
        self.Family_L.setText(_translate("Guest_signup_page", "Family"))
        self.Signup_Button.setText(_translate("Guest_signup_page", "SignUp"))
        self.Gender_L.setText(_translate("Guest_signup_page", "Gender"))
        self.BirthDate_L.setText(_translate("Guest_signup_page", "Birth Date"))
        self.male_RD.setText(_translate("Guest_signup_page", "Male"))
        self.female_RD.setText(_translate("Guest_signup_page", "Female"))
        self.Phone_L.setText(_translate("Guest_signup_page", "Phone.No"))
        self.Address_L.setText(_translate("Guest_signup_page", "Address"))
        self.National_L.setText(_translate("Guest_signup_page", "National ID"))
        self.Password_L.setText(_translate("Guest_signup_page", "Password"))
        self.Login_Button.setText(_translate("Guest_signup_page", "Login"))

    def Fill_Guest_Information(self):
        gender = 0
        if self.male_RD.isChecked():
            gender = 1

        year = self.BirthDate_DE.date().year()
        month = self.BirthDate_DE.date().month()
        day = self.BirthDate_DE.date().day()
        str_now = datetime.datetime(year, month, day).isoformat()

        if (self.Firstname_LE.text() != '') and (self.Family_LE.text() != '') and (self.Password_LE.text() != '') and \
                (self.Phone_LE.text() != '') and (self.Address_LE.text() != '') and (self.National_LE.text() != ''):
            exe_query(f""" 
                           INSERT INTO guest 
                           (Guest_Firstname,Guest_Lastname,Guest_Password,Guest_PhoneNumber,
                            Guest_Address,Guest_BirthDate,Guest_Gender,Guest_National_ID) 
                                               VALUES
                           ('{self.Firstname_LE.text()}','{self.Family_LE.text()}','{self.Password_LE.text()}',
                            '{self.Phone_LE.text()}','{self.Address_LE.text()}' ,
                            '{str_now}', {gender},'{self.National_LE.text()}'); 
                        """)

            self.Guest_Login_Window()

    def Guest_Login_Window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginPage()
        self.ui.setupUi(self.window)
        self.window.show()
