from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

from User.DB_Configuration import exe_query


class Ui_FreeRooms(object):

    def setupUi(self, FreeRooms):
        FreeRooms.setObjectName("FreeRooms")
        FreeRooms.resize(1094, 846)
        FreeRooms.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FreeRooms_DateEditOne = QtWidgets.QDateEdit(FreeRooms)
        self.FreeRooms_DateEditOne.setGeometry(QtCore.QRect(210, 120, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FreeRooms_DateEditOne.setFont(font)
        self.FreeRooms_DateEditOne.setStyleSheet("background-color: rgb(133, 196, 255);")
        self.FreeRooms_DateEditOne.setObjectName("FreeRooms_DateEditOne")
        self.FreeRooms_DateEditTwo = QtWidgets.QDateEdit(FreeRooms)
        self.FreeRooms_DateEditTwo.setGeometry(QtCore.QRect(650, 120, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FreeRooms_DateEditTwo.setFont(font)
        self.FreeRooms_DateEditTwo.setStyleSheet("background-color: rgb(133, 196, 255);")
        self.FreeRooms_DateEditTwo.setObjectName("FreeRooms_DateEditTwo")
        self.FreeRooms_From = QtWidgets.QLabel(FreeRooms)
        self.FreeRooms_From.setGeometry(QtCore.QRect(50, 120, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FreeRooms_From.setFont(font)
        self.FreeRooms_From.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FreeRooms_From.setStyleSheet("background-color: rgb(219, 255, 255);")
        self.FreeRooms_From.setFrameShape(QtWidgets.QFrame.Panel)
        self.FreeRooms_From.setAlignment(QtCore.Qt.AlignCenter)
        self.FreeRooms_From.setObjectName("FreeRooms_From")
        self.FreeRooms_To = QtWidgets.QLabel(FreeRooms)
        self.FreeRooms_To.setGeometry(QtCore.QRect(490, 120, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FreeRooms_To.setFont(font)
        self.FreeRooms_To.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FreeRooms_To.setStyleSheet("background-color: rgb(219, 255, 255);")
        self.FreeRooms_To.setFrameShape(QtWidgets.QFrame.Panel)
        self.FreeRooms_To.setAlignment(QtCore.Qt.AlignCenter)
        self.FreeRooms_To.setObjectName("FreeRooms_To")
        self.SeeFreeRooms_L = QtWidgets.QLabel(FreeRooms)
        self.SeeFreeRooms_L.setGeometry(QtCore.QRect(290, 30, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SeeFreeRooms_L.setFont(font)
        self.SeeFreeRooms_L.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SeeFreeRooms_L.setStyleSheet("background-color: rgb(255, 97, 100);")
        self.SeeFreeRooms_L.setAlignment(QtCore.Qt.AlignCenter)
        self.SeeFreeRooms_L.setObjectName("SeeFreeRooms_L")
        self.SeeFreeRooms_B = QtWidgets.QPushButton(FreeRooms)
        self.SeeFreeRooms_B.setGeometry(QtCore.QRect(910, 120, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SeeFreeRooms_B.setFont(font)
        self.SeeFreeRooms_B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SeeFreeRooms_B.setStyleSheet("background-color: rgb(208, 209, 255);")
        self.SeeFreeRooms_B.setObjectName("SeeFreeRooms_B")
        self.FreeRooms_TableWidget = QtWidgets.QTableWidget(FreeRooms)
        self.FreeRooms_TableWidget.setGeometry(QtCore.QRect(140, 200, 811, 451))
        self.FreeRooms_TableWidget.setObjectName("FreeRooms_TableWidget")
        self.FreeRooms_TableWidget.setColumnCount(6)
        self.FreeRooms_TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(120, 105, 110))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FreeRooms_TableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(FreeRooms)
        QtCore.QMetaObject.connectSlotsByName(FreeRooms)

        self.FreeRooms_TableWidget.setColumnWidth(0, 80)
        self.FreeRooms_TableWidget.setColumnWidth(1, 80)
        self.FreeRooms_TableWidget.setColumnWidth(2, 180)
        self.FreeRooms_TableWidget.setColumnWidth(3, 120)
        self.FreeRooms_TableWidget.setColumnWidth(4, 180)
        self.FreeRooms_TableWidget.setColumnWidth(5, 120)

        # Enter_Clicked
        self.SeeFreeRooms_B.clicked.connect(self.loadData)

    def retranslateUi(self, FreeRooms):
        _translate = QtCore.QCoreApplication.translate
        FreeRooms.setWindowTitle(_translate("FreeRooms", "Free Rooms"))
        self.FreeRooms_From.setText(_translate("FreeRooms", "From"))
        self.FreeRooms_To.setText(_translate("FreeRooms", "To"))
        self.SeeFreeRooms_L.setText(_translate("FreeRooms", "See Empty Rooms Between Given Dates"))
        self.SeeFreeRooms_B.setText(_translate("FreeRooms", "Enter"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FreeRooms", "Room ID"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FreeRooms", "Floor"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FreeRooms", "Price Per Night"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FreeRooms", "Beds Number"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FreeRooms", "Description"))
        item = self.FreeRooms_TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FreeRooms", "Max Capacity"))

    def loadData(self):
        year = self.FreeRooms_DateEditOne.date().year()
        month = self.FreeRooms_DateEditOne.date().month()
        day = self.FreeRooms_DateEditOne.date().day()
        Date_From = datetime.datetime(year, month, day).isoformat()

        year = self.FreeRooms_DateEditTwo.date().year()
        month = self.FreeRooms_DateEditTwo.date().month()
        day = self.FreeRooms_DateEditTwo.date().day()
        Date_To = datetime.datetime(year, month, day).isoformat()

        res = exe_query(f""" 
                     SELECT Room_ID,Floor, Price_Per_Night,no_beds,description,Maximum_Capacity FROM room
                     JOIN room_type rt on rt.room_type_id = room.room_type_id
                     WHERE Room_ID NOT IN
                     (SELECT rd.Room_ID FROM room JOIN reservation_details rd on room.Room_ID = rd.Room_ID
                     JOIN reservation r on r.Reservation_ID = rd.Reservation_ID WHERE
                     '{Date_From}' >= Reservation_CheckIn  AND '{Date_To}' <= Reservation_CheckOut )
                     AND (Room_Status_ID = 1 OR Room_Status_ID = 2 OR Room_Status_ID = 3) ; ; 
                   """)

        row = 0
        self.FreeRooms_TableWidget.setRowCount(len(res))
        for data in res:
            self.FreeRooms_TableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(data[0]))
            self.FreeRooms_TableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(data[1]))
            self.FreeRooms_TableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(data[2]))
            self.FreeRooms_TableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(data[3]))
            self.FreeRooms_TableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(data[4]))
            self.FreeRooms_TableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(data[5]))

            row += 1

        print(res)
